services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    tty: true

volumes:
  pgdata:

networks:
  cravers_hub_network:
    driver: "bridge"