spring.application.name=Craver_Hub
spring.datasource.url=jdbc:postgresql://db:5432/cravers-hub
spring.datasource.username=postgres
spring.datasource.password=example
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto = create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
server.port=8090
management.health.db.enabled=false
management.endpoints.web.exposure.include=*
spring.cache.cache-names=idempotence